### ISSUE TITLE
Formato de fecha en los comentarios

### ISSUE THREAD

**Issue by julianMondragon** [julianMondragon/TAS360#44]
Formato del comentario estándar 
--------------------------------------------------------------------------------
Se debe establecer un formato de fecha donde el nombre del MES sea con nombre Ejemplo: 
Agosto/22/2024

Se debe agregar la version al formato:
->Fecha: 
->Reportado por:  
**->Versión:**

**Comment by RasAzarim** [comment]
Se observa de forma correcta el nuevo formato de fecha
